//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostnLocated.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackMaster
    {
        public int FeedbackId { get; set; }
        public string UserId { get; set; }
        public string FeedTitle { get; set; }
        public string FeedText { get; set; }
        public Nullable<System.DateTime> FeedDate { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
