//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostnLocated.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationMaster
    {
        public int NotificationId { get; set; }
        public string NotificationText { get; set; }
        public Nullable<System.DateTime> NotificationDT { get; set; }
    }
}
