//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostnLocated.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostMaster
    {
        public int LFId { get; set; }
        public string UserId { get; set; }
        public string PostType { get; set; }
        public string GoodsCategory { get; set; }
        public Nullable<System.DateTime> DateOfFoundLost { get; set; }
        public string TimeOfFoundLost { get; set; }
        public string SpecifyAddress { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string Description { get; set; }
        public string GoodsPicName { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
