//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostnLocated.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardMaster
    {
        public int RewardId { get; set; }
        public string UserId { get; set; }
        public string Description { get; set; }
        public string DDNumber { get; set; }
        public string DDFilePic { get; set; }
        public Nullable<int> RewardAmount { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
